### ISSUE TITLE
hello, a question about BerlinMOD

### ISSUE THREAD

**Issue by Loulinghui** [MobilityDB/MobilityDB-BerlinMOD#2]
Hi, Thank you for creating MobilityDB , This is a great project.
But I encountered some problems in the process of use:

I executed berlinmod_runall.sh, But no Cars, TripsInput, Instants, Periods, Points, RegionsInput, Regions, and Trips are generated.

postgres@ubuntu:/home/mca/Desktop/data$ sh berlinmod_runall.sh
Password: 
Password: 
Password for user postgres: 
NOTICE:  installing required extension "postgis"
CREATE EXTENSION
Password for user postgres: 
CREATE EXTENSION
Execution starts at: Wed May 12 06:38:48 2021

***************************************************
           COMMAND LINE CONFIGURATION             *
***************************************************
Filename = brussels.osm
Configuration file = mapconfig_brussels.xml
host = localhost
port = 5432
dbname = brussels
username = postgres
schema= 
prefix = 
suffix = 
Don't drop tables
Don't create indexes
Don't add OSM nodes
***************************************************
Testing database connection: brussels
database connection successful: brussels
Connecting to the database
connection success

Creating tables...
TABLE: ways_vertices_pgr created ... OK.
TABLE: ways created ... OK.
TABLE: pointsofinterest created ... OK.
TABLE: configuration created ... OK.
Opening configuration file: mapconfig_brussels.xml
    Parsing configuration

Exporting configuration ...
  - Done 
Counting lines ...
  - Done 
Opening data file: brussels.osm	total lines: 9565284
    Parsing data

End Of file

    Finish Parsing data

Adding auxiliary tables to database...

Export Ways ...
    Processing 432717 ways:
[**|                                                ] (4%) Total processed: 20000	 Vertices inserted: 32633	Split ways inserted 31654
[****|                                              ] (9%) Total processed: 40000	 Vertices inserted: 7037	Split ways inserted 8134
[******|                                            ] (13%) Total processed: 60000	 Vertices inserted: 4185	Split ways inserted 5060
[*********|                                         ] (18%) Total processed: 80000	 Vertices inserted: 4006	Split ways inserted 5132
[***********|                                       ] (23%) Total processed: 100000	 Vertices inserted: 3150	Split ways inserted 4182
[*************|                                     ] (27%) Total processed: 120000	 Vertices inserted: 178	Split ways inserted 220
[****************|                                  ] (32%) Total processed: 140000	 Vertices inserted: 131	Split ways inserted 240
[******************|                                ] (36%) Total processed: 160000	 Vertices inserted: 102	Split ways inserted 150
[********************|                              ] (41%) Total processed: 180000	 Vertices inserted: 59	Split ways inserted 95
[***********************|                           ] (46%) Total processed: 200000	 Vertices inserted: 334	Split ways inserted 586
[*************************|                         ] (50%) Total processed: 220000	 Vertices inserted: 268	Split ways inserted 408
[***************************|                       ] (55%) Total processed: 240000	 Vertices inserted: 467	Split ways inserted 677
[******************************|                    ] (60%) Total processed: 260000	 Vertices inserted: 339	Split ways inserted 492
[********************************|                  ] (64%) Total processed: 280000	 Vertices inserted: 504	Split ways inserted 769
[**********************************|                ] (69%) Total processed: 300000	 Vertices inserted: 534	Split ways inserted 876
[************************************|              ] (73%) Total processed: 320000	 Vertices inserted: 1951	Split ways inserted 3057
[***************************************|           ] (78%) Total processed: 340000	 Vertices inserted: 2075	Split ways inserted 3463
[*****************************************|         ] (83%) Total processed: 360000	 Vertices inserted: 3398	Split ways inserted 5511
[*******************************************|       ] (87%) Total processed: 380000	 Vertices inserted: 2325	Split ways inserted 3764
[**********************************************|    ] (92%) Total processed: 400000	 Vertices inserted: 1644	Split ways inserted 2954
[************************************************|  ] (97%) Total processed: 420000	 Vertices inserted: 1523	Split ways inserted 2602
[**************************************************|] (100%) Total processed: 432717	 Vertices inserted: 1582	Split ways inserted 2784

Creating indexes ...

Processing Points of Interest ...
#########################
size of streets: 432717
Execution started at: Wed May 12 06:38:48 2021
Execution ended at:   Wed May 12 06:39:12 2021
Elapsed time: 24.113 Seconds.
User CPU time: -> 10.0416 seconds
#########################
osm2pgsql version 1.2.1 (64 bit id space)

Password:
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=3
Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: postgres
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: Cannot detect file format. Try using -r.
berlinmod_runall.sh: 16: cannot create brussels.tar: Permission denied
pg_restore: connecting to database for restore
pg_restore: creating DATABASE "brussels"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 7649; 1262 120467 DATABASE brussels postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  database "brussels" already exists
    Command was: CREATE DATABASE brussels WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';

pg_restore: connecting to new database "brussels"
pg_restore: creating EXTENSION "postgis"
pg_restore: creating COMMENT "EXTENSION postgis"
pg_restore: creating EXTENSION "mobilitydb"
pg_restore: creating COMMENT "EXTENSION mobilitydb"
pg_restore: creating EXTENSION "pgrouting"
pg_restore: creating COMMENT "EXTENSION pgrouting"
pg_restore: creating TABLE "public.configuration"
pg_restore: [archiver (db)] Error from TOC entry 223; 1259 126199 TABLE configuration postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "configuration" already exists
    Command was: CREATE TABLE public.configuration (
    id integer NOT NULL,
    tag_id integer,
    tag_key text,
    tag_value text,
    priority double precision,
    maxspeed double precision,
    maxspeed_forward double precision,
    maxspeed_backward double precision,
    force character(1)
)
WITH (autovacuum_enabled='false');

pg_restore: creating SEQUENCE "public.configuration_id_seq"
pg_restore: [archiver (db)] Error from TOC entry 222; 1259 126197 SEQUENCE configuration_id_seq postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "configuration_id_seq" already exists
    Command was: CREATE SEQUENCE public.configuration_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

pg_restore: creating SEQUENCE OWNED BY "public.configuration_id_seq"
pg_restore: creating TABLE "public.planet_osm_line"
pg_restore: [archiver (db)] Error from TOC entry 225; 1259 126549 TABLE planet_osm_line postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "planet_osm_line" already exists
    Command was: CREATE UNLOGGED TABLE public.planet_osm_line (
    osm_id bigint,
    access text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    admin_level text,
    aerialway text,
    aeroway text,
    amenity text,
    area text,
    barrier text,
    bicycle text,
    brand text,
    bridge text,
    boundary text,
    building text,
    construction text,
    covered text,
    culvert text,
    cutting text,
    denomination text,
    disused text,
    embankment text,
    foot text,
    "generator:source" text,
    harbour text,
    highway text,
    historic text,
    horse text,
    intermittent text,
    junction text,
    landuse text,
    layer text,
    leisure text,
    lock text,
    man_made text,
    military text,
    motorcar text,
    name text,
    "natural" text,
    office text,
    oneway text,
    operator text,
    place text,
    population text,
    power text,
    power_source text,
    public_transport text,
    railway text,
    ref text,
    religion text,
    route text,
    service text,
    shop text,
    sport text,
    surface text,
    toll text,
    tourism text,
    "tower:type" text,
    tracktype text,
    tunnel text,
    water text,
    waterway text,
    wetland text,
    width text,
    wood text,
    z_order integer,
    way_area real,
    way public.geometry(LineString,3857)
)
WITH (autovacuum_enabled='false');

pg_restore: creating TABLE "public.planet_osm_point"
pg_restore: [archiver (db)] Error from TOC entry 224; 1259 126543 TABLE planet_osm_point postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "planet_osm_point" already exists
    Command was: CREATE UNLOGGED TABLE public.planet_osm_point (
    osm_id bigint,
    access text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    admin_level text,
    aerialway text,
    aeroway text,
    amenity text,
    area text,
    barrier text,
    bicycle text,
    brand text,
    bridge text,
    boundary text,
    building text,
    capital text,
    construction text,
    covered text,
    culvert text,
    cutting text,
    denomination text,
    disused text,
    ele text,
    embankment text,
    foot text,
    "generator:source" text,
    harbour text,
    highway text,
    historic text,
    horse text,
    intermittent text,
    junction text,
    landuse text,
    layer text,
    leisure text,
    lock text,
    man_made text,
    military text,
    motorcar text,
    name text,
    "natural" text,
    office text,
    oneway text,
    operator text,
    place text,
    population text,
    power text,
    power_source text,
    public_transport text,
    railway text,
    ref text,
    religion text,
    route text,
    service text,
    shop text,
    sport text,
    surface text,
    toll text,
    tourism text,
    "tower:type" text,
    tunnel text,
    water text,
    waterway text,
    wetland text,
    width text,
    wood text,
    z_order integer,
    way public.geometry(Point,3857)
)
WITH (autovacuum_enabled='false');

pg_restore: creating TABLE "public.planet_osm_polygon"
pg_restore: [archiver (db)] Error from TOC entry 226; 1259 126555 TABLE planet_osm_polygon postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "planet_osm_polygon" already exists
    Command was: CREATE UNLOGGED TABLE public.planet_osm_polygon (
    osm_id bigint,
    access text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    admin_level text,
    aerialway text,
    aeroway text,
    amenity text,
    area text,
    barrier text,
    bicycle text,
    brand text,
    bridge text,
    boundary text,
    building text,
    construction text,
    covered text,
    culvert text,
    cutting text,
    denomination text,
    disused text,
    embankment text,
    foot text,
    "generator:source" text,
    harbour text,
    highway text,
    historic text,
    horse text,
    intermittent text,
    junction text,
    landuse text,
    layer text,
    leisure text,
    lock text,
    man_made text,
    military text,
    motorcar text,
    name text,
    "natural" text,
    office text,
    oneway text,
    operator text,
    place text,
    population text,
    power text,
    power_source text,
    public_transport text,
    railway text,
    ref text,
    religion text,
    route text,
    service text,
    shop text,
    sport text,
    surface text,
    toll text,
    tourism text,
    "tower:type" text,
    tracktype text,
    tunnel text,
    water text,
    waterway text,
    wetland text,
    width text,
    wood text,
    z_order integer,
    way_area real,
    way public.geometry(Geometry,3857)
)
WITH (autovacuum_enabled='false');

pg_restore: creating TABLE "public.planet_osm_roads"
pg_restore: [archiver (db)] Error from TOC entry 227; 1259 126561 TABLE planet_osm_roads postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "planet_osm_roads" already exists
    Command was: CREATE UNLOGGED TABLE public.planet_osm_roads (
    osm_id bigint,
    access text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    admin_level text,
    aerialway text,
    aeroway text,
    amenity text,
    area text,
    barrier text,
    bicycle text,
    brand text,
    bridge text,
    boundary text,
    building text,
    construction text,
    covered text,
    culvert text,
    cutting text,
    denomination text,
    disused text,
    embankment text,
    foot text,
    "generator:source" text,
    harbour text,
    highway text,
    historic text,
    horse text,
    intermittent text,
    junction text,
    landuse text,
    layer text,
    leisure text,
    lock text,
    man_made text,
    military text,
    motorcar text,
    name text,
    "natural" text,
    office text,
    oneway text,
    operator text,
    place text,
    population text,
    power text,
    power_source text,
    public_transport text,
    railway text,
    ref text,
    religion text,
    route text,
    service text,
    shop text,
    sport text,
    surface text,
    toll text,
    tourism text,
    "tower:type" text,
    tracktype text,
    tunnel text,
    water text,
    waterway text,
    wetland text,
    width text,
    wood text,
    z_order integer,
    way_area real,
    way public.geometry(LineString,3857)
)
WITH (autovacuum_enabled='false');

pg_restore: creating TABLE "public.pointsofinterest"
pg_restore: [archiver (db)] Error from TOC entry 221; 1259 126190 TABLE pointsofinterest postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pointsofinterest" already exists
    Command was: CREATE TABLE public.pointsofinterest (
    pid bigint NOT NULL,
    osm_id bigint,
    vertex_id bigint,
    edge_id bigint,
    side character(1),
    fraction double precision,
    length_m double precision,
    tag_name text,
    tag_value text,
    name text,
    the_geom public.geometry(Point,4326),
    new_geom public.geometry(Point,4326)
)
WITH (autovacuum_enabled='false');

pg_restore: creating SEQUENCE "public.pointsofinterest_pid_seq"
pg_restore: [archiver (db)] Error from TOC entry 220; 1259 126188 SEQUENCE pointsofinterest_pid_seq postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pointsofinterest_pid_seq" already exists
    Command was: CREATE SEQUENCE public.pointsofinterest_pid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

pg_restore: creating SEQUENCE OWNED BY "public.pointsofinterest_pid_seq"
pg_restore: creating TABLE "public.ways"
pg_restore: [archiver (db)] Error from TOC entry 219; 1259 126180 TABLE ways postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways" already exists
    Command was: CREATE TABLE public.ways (
    gid bigint NOT NULL,
    osm_id bigint,
    tag_id integer,
    length double precision,
    length_m double precision,
    name text,
    source bigint,
    target bigint,
    source_osm bigint,
    target_osm bigint,
    cost double precision,
    reverse_cost double precision,
    cost_s double precision,
    reverse_cost_s double precision,
    rule text,
    one_way integer,
    oneway text,
    x1 double precision,
    y1 double precision,
    x2 double precision,
    y2 double precision,
    maxspeed_forward double precision,
    maxspeed_backward double precision,
    priority double precision DEFAULT 1,
    the_geom public.geometry(LineString,4326)
)
WITH (autovacuum_enabled='false');

pg_restore: creating SEQUENCE "public.ways_gid_seq"
pg_restore: [archiver (db)] Error from TOC entry 218; 1259 126178 SEQUENCE ways_gid_seq postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_gid_seq" already exists
    Command was: CREATE SEQUENCE public.ways_gid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

pg_restore: creating SEQUENCE OWNED BY "public.ways_gid_seq"
pg_restore: creating TABLE "public.ways_vertices_pgr"
pg_restore: [archiver (db)] Error from TOC entry 217; 1259 126171 TABLE ways_vertices_pgr postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_vertices_pgr" already exists
    Command was: CREATE TABLE public.ways_vertices_pgr (
    id bigint NOT NULL,
    osm_id bigint,
    eout integer,
    lon numeric(11,8),
    lat numeric(11,8),
    cnt integer,
    chk integer,
    ein integer,
    the_geom public.geometry(Point,4326)
)
WITH (autovacuum_enabled='false');

pg_restore: creating SEQUENCE "public.ways_vertices_pgr_id_seq"
pg_restore: [archiver (db)] Error from TOC entry 216; 1259 126169 SEQUENCE ways_vertices_pgr_id_seq postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_vertices_pgr_id_seq" already exists
    Command was: CREATE SEQUENCE public.ways_vertices_pgr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

pg_restore: creating SEQUENCE OWNED BY "public.ways_vertices_pgr_id_seq"
pg_restore: creating DEFAULT "public.configuration id"
pg_restore: creating DEFAULT "public.pointsofinterest pid"
pg_restore: creating DEFAULT "public.ways gid"
pg_restore: creating DEFAULT "public.ways_vertices_pgr id"
pg_restore: processing data for table "public.configuration"
pg_restore: [archiver (db)] Error from TOC entry 7639; 0 126199 TABLE DATA configuration postgres
pg_restore: [archiver (db)] COPY failed for table "configuration": ERROR:  duplicate key value violates unique constraint "configuration_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY configuration, line 1
pg_restore: processing data for table "public.planet_osm_line"
pg_restore: processing data for table "public.planet_osm_point"
pg_restore: processing data for table "public.planet_osm_polygon"
pg_restore: processing data for table "public.planet_osm_roads"
pg_restore: processing data for table "public.pointsofinterest"
pg_restore: processing data for table "public.spatial_ref_sys"
pg_restore: processing data for table "public.ways"
pg_restore: [archiver (db)] Error from TOC entry 7635; 0 126180 TABLE DATA ways postgres
pg_restore: [archiver (db)] COPY failed for table "ways": ERROR:  duplicate key value violates unique constraint "ways_pkey"
DETAIL:  Key (gid)=(1) already exists.
CONTEXT:  COPY ways, line 1
pg_restore: processing data for table "public.ways_vertices_pgr"
pg_restore: [archiver (db)] Error from TOC entry 7633; 0 126171 TABLE DATA ways_vertices_pgr postgres
pg_restore: [archiver (db)] COPY failed for table "ways_vertices_pgr": ERROR:  duplicate key value violates unique constraint "ways_vertices_pgr_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY ways_vertices_pgr, line 1
pg_restore: executing SEQUENCE SET configuration_id_seq
pg_restore: executing SEQUENCE SET pointsofinterest_pid_seq
pg_restore: executing SEQUENCE SET ways_gid_seq
pg_restore: executing SEQUENCE SET ways_vertices_pgr_id_seq
pg_restore: creating CONSTRAINT "public.configuration configuration_pkey"
pg_restore: [archiver (db)] Error from TOC entry 7496; 2606 126502 CONSTRAINT configuration configuration_pkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  multiple primary keys for table "configuration" are not allowed
    Command was: ALTER TABLE ONLY public.configuration
    ADD CONSTRAINT configuration_pkey PRIMARY KEY (id);

pg_restore: creating CONSTRAINT "public.configuration configuration_tag_id_key"
pg_restore: [archiver (db)] Error from TOC entry 7498; 2606 126504 CONSTRAINT configuration configuration_tag_id_key postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "configuration_tag_id_key" already exists
    Command was: ALTER TABLE ONLY public.configuration
    ADD CONSTRAINT configuration_tag_id_key UNIQUE (tag_id);

pg_restore: creating CONSTRAINT "public.pointsofinterest pointsofinterest_osm_id_key"
pg_restore: [archiver (db)] Error from TOC entry 7491; 2606 126542 CONSTRAINT pointsofinterest pointsofinterest_osm_id_key postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pointsofinterest_osm_id_key" already exists
    Command was: ALTER TABLE ONLY public.pointsofinterest
    ADD CONSTRAINT pointsofinterest_osm_id_key UNIQUE (osm_id);

pg_restore: creating CONSTRAINT "public.pointsofinterest pointsofinterest_pkey"
pg_restore: [archiver (db)] Error from TOC entry 7493; 2606 126539 CONSTRAINT pointsofinterest pointsofinterest_pkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  multiple primary keys for table "pointsofinterest" are not allowed
    Command was: ALTER TABLE ONLY public.pointsofinterest
    ADD CONSTRAINT pointsofinterest_pkey PRIMARY KEY (pid);

pg_restore: creating CONSTRAINT "public.ways ways_pkey"
pg_restore: [archiver (db)] Error from TOC entry 7488; 2606 126511 CONSTRAINT ways ways_pkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  multiple primary keys for table "ways" are not allowed
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_pkey PRIMARY KEY (gid);

pg_restore: creating CONSTRAINT "public.ways_vertices_pgr ways_vertices_pgr_osm_id_key"
pg_restore: [archiver (db)] Error from TOC entry 7483; 2606 126508 CONSTRAINT ways_vertices_pgr ways_vertices_pgr_osm_id_key postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_vertices_pgr_osm_id_key" already exists
    Command was: ALTER TABLE ONLY public.ways_vertices_pgr
    ADD CONSTRAINT ways_vertices_pgr_osm_id_key UNIQUE (osm_id);

pg_restore: creating CONSTRAINT "public.ways_vertices_pgr ways_vertices_pgr_pkey"
pg_restore: [archiver (db)] Error from TOC entry 7485; 2606 126506 CONSTRAINT ways_vertices_pgr ways_vertices_pgr_pkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  multiple primary keys for table "ways_vertices_pgr" are not allowed
    Command was: ALTER TABLE ONLY public.ways_vertices_pgr
    ADD CONSTRAINT ways_vertices_pgr_pkey PRIMARY KEY (id);

pg_restore: creating INDEX "public.pointsofinterest_the_geom_idx"
pg_restore: [archiver (db)] Error from TOC entry 7494; 1259 126540 INDEX pointsofinterest_the_geom_idx postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "pointsofinterest_the_geom_idx" already exists
    Command was: CREATE INDEX pointsofinterest_the_geom_idx ON public.pointsofinterest USING gist (the_geom);

pg_restore: creating INDEX "public.ways_the_geom_idx"
pg_restore: [archiver (db)] Error from TOC entry 7489; 1259 126537 INDEX ways_the_geom_idx postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_the_geom_idx" already exists
    Command was: CREATE INDEX ways_the_geom_idx ON public.ways USING gist (the_geom);

pg_restore: creating INDEX "public.ways_vertices_pgr_the_geom_idx"
pg_restore: [archiver (db)] Error from TOC entry 7486; 1259 126509 INDEX ways_vertices_pgr_the_geom_idx postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "ways_vertices_pgr_the_geom_idx" already exists
    Command was: CREATE INDEX ways_vertices_pgr_the_geom_idx ON public.ways_vertices_pgr USING gist (the_geom);

pg_restore: creating FK CONSTRAINT "public.ways ways_source_fkey"
pg_restore: [archiver (db)] Error from TOC entry 7499; 2606 126512 FK CONSTRAINT ways ways_source_fkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "ways_source_fkey" for relation "ways" already exists
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_source_fkey FOREIGN KEY (source) REFERENCES public.ways_vertices_pgr(id);

pg_restore: creating FK CONSTRAINT "public.ways ways_source_osm_fkey"
pg_restore: [archiver (db)] Error from TOC entry 7501; 2606 126522 FK CONSTRAINT ways ways_source_osm_fkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "ways_source_osm_fkey" for relation "ways" already exists
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_source_osm_fkey FOREIGN KEY (source_osm) REFERENCES public.ways_vertices_pgr(osm_id);

pg_restore: creating FK CONSTRAINT "public.ways ways_tag_id_fkey"
pg_restore: [archiver (db)] Error from TOC entry 7503; 2606 126532 FK CONSTRAINT ways ways_tag_id_fkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "ways_tag_id_fkey" for relation "ways" already exists
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.configuration(tag_id);

pg_restore: creating FK CONSTRAINT "public.ways ways_target_fkey"
pg_restore: [archiver (db)] Error from TOC entry 7500; 2606 126517 FK CONSTRAINT ways ways_target_fkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "ways_target_fkey" for relation "ways" already exists
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_target_fkey FOREIGN KEY (target) REFERENCES public.ways_vertices_pgr(id);

pg_restore: creating FK CONSTRAINT "public.ways ways_target_osm_fkey"
pg_restore: [archiver (db)] Error from TOC entry 7502; 2606 126527 FK CONSTRAINT ways ways_target_osm_fkey postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "ways_target_osm_fkey" for relation "ways" already exists
    Command was: ALTER TABLE ONLY public.ways
    ADD CONSTRAINT ways_target_osm_fkey FOREIGN KEY (target_osm) REFERENCES public.ways_vertices_pgr(osm_id);

WARNING: errors ignored on restore: 31
Password for user postgres: 
psql:brussels_preparedata.sql:27: NOTICE:  table "edges" does not exist, skipping
DROP TABLE
SELECT 82810
psql:brussels_preparedata.sql:37: NOTICE:  table "nodes" does not exist, skipping
DROP TABLE
SELECT 66781
CREATE INDEX
CREATE INDEX
CREATE INDEX
UPDATE 82810
DELETE 1984
CREATE INDEX
CREATE INDEX
psql:brussels_preparedata.sql:83: NOTICE:  table "communes" does not exist, skipping
DROP TABLE
SELECT 19
psql:brussels_preparedata.sql:108: NOTICE:  table "communesgeom" does not exist, skipping
DROP TABLE
SELECT 0
UPDATE 0
DELETE 0
ALTER TABLE
UPDATE 0
ALTER TABLE
UPDATE 19
psql:brussels_preparedata.sql:171: NOTICE:  table "saintjosse" does not exist, skipping
DROP TABLE
DROP TABLE
psql:brussels_preparedata.sql:176: NOTICE:  table "homeregions" does not exist, skipping
DROP TABLE
SELECT 19
CREATE INDEX
psql:brussels_preparedata.sql:185: NOTICE:  table "workregions" does not exist, skipping
DROP TABLE
SELECT 19
CREATE INDEX
psql:brussels_preparedata.sql:194: NOTICE:  table "homenodes" does not exist, skipping
DROP TABLE
SELECT 0
CREATE INDEX
psql:brussels_preparedata.sql:202: NOTICE:  table "worknodes" does not exist, skipping
DROP TABLE
SELECT 0
CREATE INDEX
Password for user postgres: 
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:309: NOTICE:  function berlinmod_roadcategory() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:327: NOTICE:  type "step" does not exist, skipping
DROP TYPE
CREATE TYPE
psql:berlinmod_datagenerator.sql:336: NOTICE:  function createpath() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:380: NOTICE:  function createtrip() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:713: NOTICE:  function berlinmod_selecthomenode() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:787: NOTICE:  function berlinmod_selectdestnode() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:817: NOTICE:  function berlinmod_createlicence() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:843: NOTICE:  function berlinmod_vehicletype() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:871: NOTICE:  function berlinmod_vehiclemodel() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:901: NOTICE:  function berlinmod_createtrips() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
psql:berlinmod_datagenerator.sql:1078: NOTICE:  function berlinmod_generate() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION
Password for user postgres: 
INFO:  ------------------------------------------------------------------
INFO:  Starting the BerlinMOD data generator with scale factor 0.05
INFO:  ------------------------------------------------------------------
INFO:  Parameters:
INFO:  ------------
INFO:  No. of vehicles = 447, No. of days = 8, Start day = 2020-06-01
INFO:  Path mode = Fastest Path, Disturb data = f
INFO:  Verbosity = minimal, Trip generation = C
INFO:  Execution started at 2021-05-12 06:39:34.166817-07
INFO:  ------------------------------------------------------------------
INFO:  Creating the Destinations table
NOTICE:  table "destinations" does not exist, skipping
INFO:  Creating the Vehicle, Licences, and Neighbourhood tables
NOTICE:  table "vehicle" does not exist, skipping
NOTICE:  table "licences" does not exist, skipping
NOTICE:  table "neighbourhood" does not exist, skipping
INFO:  Creating the QueryPoints and QueryRegions tables
NOTICE:  table "querypoints" does not exist, skipping
NOTICE:  table "queryregions" does not exist, skipping
INFO:  Creating the QueryInstants and QueryPeriods tables
NOTICE:  table "queryinstants" does not exist, skipping
NOTICE:  table "queryperiods" does not exist, skipping
INFO:  Creating the LeisureTrip table
NOTICE:  table "leisuretrip" does not exist, skipping
INFO:  Creation of the Paths table started at 2021-05-12 06:39:38.550869-07
NOTICE:  table "paths" does not exist, skipping
INFO:  Creation of the Trips table started at 2021-05-12 06:39:55.697622-07
NOTICE:  table "trips" does not exist, skipping
INFO:    Vehicles 1 to 100
INFO:    Vehicles 101 to 200
INFO:    Vehicles 201 to 300
INFO:    Vehicles 301 to 400
INFO:    Vehicles 401 to 447
INFO:  ------------------------------------------------------------------
INFO:  Execution started at 2021-05-12 06:39:34.166817-07
INFO:  Execution finished at 2021-05-12 06:40:27.653865-07
INFO:  Execution time 00:00:53.487048
INFO:  Call to pgRouting with 4963 paths lasted 00:00:16.948261
INFO:  Number of trips generated 9437
INFO:  ------------------------------------------------------------------
 berlinmod_generate 
--------------------
 THE END
(1 row)

Password for user postgres: 
psql:berlinmod_r_queries.sql:33: NOTICE:  function berlinmod_r_queries() does not exist, skipping
DROP FUNCTION
CREATE FUNCTION

This is the whole process of code execution. I want to use BerlinMOD to benchmark MobilityDB , and some of the generated data seems to be missing? I hope you can answer my confusion in your free time 

                                                                                                                                                                          Thank you.

**Comment by mschoema** [comment]
Please excuse us for the inactivity.
We updated the repo in the mean time, so please let us know if you still encounter this problem.
Closing the issue, feel free to reopen if needed.
